development:
  adapter: postgresql
  encoding: utf8
  database: betterleite_development
  pool: 5
  username: postgres
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: betterleite_test
  pool: 5
  username: postgres
  min_messages: WARNING
  host: localhost
  template: template0

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
